# Generated by Django 4.2.7 on 2023-11-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
